### ISSUE TITLE
Заказчик. Форма создания нового заказа 

### ISSUE THREAD

**Issue by CadiasDi** [Ha1f15ch/SiteOrdersForClientByEmploy-rs#12]
Создать новый заказ -> Выбор услуги или специалиста -> Выбор дополнительных уточнений по услуге ->Приложить описание/фото  -> Указать дату начало и конца -> Создать заказ.

(Нужно ли указывать сразу стоимость заказа?) 

После создания заказа ему присваивается уникальный номер и дата создания.
Он будет отображаться у пользователя во вкладке - "Мои заказы", где будет возможность его редактирования/удаления.

**Comment by Ha1f15ch** [comment]
Предлагаю данную задачу подержать до окончательного описания моделей пользователей - 
1. Заказчика
2. Исполнителя
3. Услуги #9

**Comment by Ha1f15ch** [comment]
Будет реализовано в рамках задачи - #37
