### ISSUE TITLE
Основные элементы меню на сайте, при авторизации в качестве исполнителя.

### ISSUE THREAD

**Issue by CadiasDi** [Ha1f15ch/SiteOrdersForClientByEmploy-rs#7]
### Заголовки на страницах.

При авторизации как *исполнитель* будет отображаться меню модулей:
1. Заказ. 
2. Мои чаты. (обсуждение с заказчиками выбранных заказов, где Я - исполнитель был выбран заказчиком)
3. Моя анкета.
4. Переход на главную страницу

**Comment by Ha1f15ch** [comment]
Оперируем сущностями: 
1. Исполнитель
2. Заказчик
3. Заказ

**Comment by Ha1f15ch** [comment]
Будет реализовано в рамках задачи - #36
