### ISSUE TITLE
Исполнитель. Основные элементы интерфейса на вкладке "Заказы". 

### ISSUE THREAD

**Issue by CadiasDi** [Ha1f15ch/SiteOrdersForClientByEmploy-rs#8]
### Основной сценарий

1. Поиск заказов -> Выбор направления -> Просмотр подробной информации по какому-то конкретному заказу заказчика.
2. Блок фильтров, где можно указать соответствующие параметры фильтра, для сужения поиска подходящих заказов

### Альтернативный сценарий
1. Если при поиске заказов, в результате ничего не находится -> Сообщается о том, что "Заказов нет"

**Comment by Ha1f15ch** [comment]
Будет реализовано в задаче - #36
